# Generated by Django 3.0.4 on 2020-05-29 01:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='subheader',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
