# Generated by Django 3.0.4 on 2020-05-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20200529_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'ordering': ['price']},
        ),
    ]
