# Generated by Django 3.0.4 on 2020-06-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20200529_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
