# Generated by Django 3.0.4 on 2020-06-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_storeitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitem',
            options={'ordering': ['order']},
        ),
    ]
